Wrap refs with defaults in an allOf
smithy-lang/smithy pull request #1887
Opened 2023-07-27 23:17 UTC by srchase

Fixes https://github.com/smithy-lang/smithy/issues/1844.

According to both the [3.1.0 spec](https://spec.openapis.org/oas/latest.html#referenceObject), and the [3.0.2 spec](https://spec.openapis.org/oas/v3.0.2#referenceObject), additional fields on `referenceObjects` are ignored.

This PR changes the JsonSchemaShapeVisitor to wrap any members with an `@default` trait applied which target a `$ref` with an `allOf` so that the default can be handled correctly by OpenAPI.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-07-28 01:57 UTC, mtdowling commented
Can you test this to make sure it works with APIGW?

2023-07-28 02:30 UTC, mtdowling commented on smithy-jsonschema/src/test/resources/software/amazon/smithy/jsonschema/default-values.jsonschema.v07.json
> +                        }
I guess this is a better way to do member documentation traits too

2023-07-28 16:19 UTC, srchase commented
> Can you test this to make sure it works with APIGW?

Updated the issue description with API Gateway testing.

2023-07-31 20:17 UTC, mtdowling requested changes

2023-07-31 20:17 UTC, mtdowling commented on docs/source-2.0/guides/converting-to-openapi.rst
> +enableDefaultValues (``boolean``)
I'd make this `disableDefaultValues` and default it to `false`. booleans with `true` default values are unintutitive.

2023-07-31 20:59 UTC, mtdowling approved these changes

2023-07-31 21:34 UTC, merged