Add progress tracker and message for CLI while cloning a template
smithy-lang/smithy pull request #1888
Opened 2023-07-28 15:32 UTC by hpmellema

*Description of changes:*
Adds a progress tracker class that can be used to execute a progress tracker for the CLI while waiting for a set of commands to execute. This PR adds the progress tracker to cloning of templates in the init command as that action can take multiple seconds to complete.

Additional loading bars and progress tracker styles could be added in the future.

Example Execution gif: 
![cli](https://github.com/smithy-lang/smithy/assets/124718352/54fb976b-9f62-4294-b394-866d583e80ed)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-07-28 15:43 UTC, mtdowling commented on smithy-cli/src/main/java/software/amazon/smithy/cli/ProgressTracker.java
> +public final class ProgressTracker implements AutoCloseable {
I'd make the progress stuff all internal since if possible

2023-07-31 14:52 UTC, mtdowling requested changes

2023-07-31 16:35 UTC, hpmellema commented on smithy-cli/src/main/java/software/amazon/smithy/cli/ProgressStyle.java
> +public interface ProgressStyle {
Updated to add the integer. I can take a look at adding a `eventCounter` progress tracker style and tracker to the ModelBuilder as a separate PR.

2023-07-31 16:47 UTC, mtdowling approved these changes
This works, thanks. I think we can improve the style/updater APIs in the future to improve them a bit more (e.g., one idea is to make the update value a generic parameter of the style and update class, then allow update messages to be sent to the updater which then sends it to the styler, allowing progress bars, messages, etc).

2023-07-31 16:52 UTC, merged