Mitigate possible NSE exception in PrivateAccessValidator.java
smithy-lang/smithy pull request #2015
Opened 2023-10-21 20:48 UTC by jyoo980

*Issue #, if available:* n/a

*Description of changes:*

Within `PrivateAccessValidator#getPrivateAccessValiationEvent`, an unchecked call to `Optional#get` occurs. This might throw a `NoSuchElementException` if the optional is indeed empty.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-10-22 01:18 UTC, mtdowling requested changes
Thanks for submitting this. Did you run into this issue in practice? By the time this validator is invoked, all model references have been validated. Given this, I think a more tactical fix is to change the call to .get() the neighbor to use expectNeighborShape instead. This way it throws a more useful error message and doesn’t need the extra complexity. See https://github.com/smithy-lang/smithy/blob/32ff2c35075aa0f549c31cd5e4987c3f6c2d7320/smithy-model/src/main/java/software/amazon/smithy/model/neighbor/Relationship.java#L117

2023-10-23 16:37 UTC, jyoo980 commented
Thanks for the review, @mtdowling; I didn't mean for you to look at this over the weekend, apologies.

I haven't seen the error in-practice, but it was reported by a static analysis tool after I ran a compilation locally. I'm happy to help improve the codebase if this is something you would find useful. Are there any places in the code in particular that actually _might_ be at risk of `NoSuchElementException`?

2023-10-24 15:28 UTC, mtdowling commented
Thanks for updating. Generally any place that we use `.get()` right now is probably fine and rather than convert to returning optionals or additional conditionals, we could switch to using these kinds of expect* style methods when available or using something like orElseThrow.

2023-10-24 15:40 UTC, jyoo980 commented
Got it, thanks! I'll fix the checkstyle errors shortly.

2023-10-26 17:04 UTC, mtdowling approved these changes

2023-10-26 17:04 UTC, merged

2023-10-26 17:04 UTC, mtdowling commented
Thanks!