Bump version to 1.41.0
smithy-lang/smithy pull request #2035
Opened 2023-11-08 18:02 UTC by haydenbaker

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-11-08 18:23 UTC, hpmellema commented on CHANGELOG.md
> +* Added new trait for defining IAM actions, which consolidates and therefore deprecates several older IAM traits. ([#2034](https://github.com/smithy-lang/smithy/pull/2034))
```suggestion
* Added new trait for defining IAM actions, which consolidates and deprecates several older IAM traits. ([#2034](https://github.com/smithy-lang/smithy/pull/2034)) 
```

2023-11-08 19:12 UTC, hpmellema approved these changes

2023-11-08 19:27 UTC, syall approved these changes

2023-11-08 23:57 UTC, kstich requested changes

2023-11-08 23:57 UTC, kstich commented on CHANGELOG.md
> +### Features
Needs an update for #2036

2023-11-09 19:08 UTC, kstich approved these changes

2023-11-09 19:09 UTC, merged