aws.iam Document tidy and layout to match Principal, Action, Resource, Condition (PARC) order
smithy-lang/smithy pull request #2055
Opened 2023-11-27 15:54 UTC by 0xjjoyy

*Issue #, if available:*

*Description of changes:*

1. Layout to match Principal, Action, Resource, Condition (PARC) order
2. Tidy the condition key traits layout
3. Update to use `myservice` instead of `otherservice` for condition keys, as condition keys should reference the same service.
4. Capitalization of titles

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-11-27 20:58 UTC, hpmellema approved these changes

2023-11-27 20:58 UTC, hpmellema commented on docs/source-2.0/aws/aws-iam.rst
> +
nit: extra whitespace?

2023-11-27 21:05 UTC, kstich requested changes

2023-11-27 21:05 UTC, kstich commented on docs/source-2.0/aws/aws-iam.rst
> +Principal Traits
```suggestion
Principal traits
```

Our spec uses titles like this, [see "Constraint traits"](https://smithy.io/2.0/spec/constraint-traits.html).

2023-11-27 21:05 UTC, kstich commented on docs/source-2.0/aws/aws-iam.rst
> +Action Traits
```suggestion
Action traits
```

2023-11-27 21:05 UTC, kstich commented on docs/source-2.0/aws/aws-iam.rst
> +Condition Key Traits
```suggestion
Condition key traits
```

2023-11-27 21:05 UTC, kstich commented on docs/source-2.0/aws/aws-iam.rst
> +
```suggestion
```

2023-11-27 21:05 UTC, kstich commented on docs/source-2.0/aws/aws-iam.rst
>  Deriving Condition Keys
```suggestion
Deriving condition keys
```

2023-11-27 21:05 UTC, kstich commented on docs/source-2.0/aws/aws-iam.rst
> +``aws.iam#disableConditionKeyInference`` trait
This trait needs to be before the "Deriving condition keys" section, as it is mentioned there.

2023-11-28 05:22 UTC, 0xjjoyy commented on docs/source-2.0/aws/aws-iam.rst
> +
accepted the proposed change below

2024-01-09 22:41 UTC, closed without merging