Add backticks to diff messages for trait changes
smithy-lang/smithy pull request #2075
Opened 2023-12-15 14:43 UTC by rchache

*Description of changes:*
Adds backticks (or triple backticks) around trait values within diff event messages. This better supports markdown rendering of the messages.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-12-15 15:09 UTC, rchache commented
Tests fail since I used System.lineSeparator() instead of "\n", but the testcases use "\n". Should I change my code to use "\n" or change the testcases to check for System.lineSeparator()?

2023-12-18 18:34 UTC, mtdowling requested changes
For the failing tests, we usually fix the test cases to normalize line endings when we run into these issues. We want to use the right line separator when we write output, but assertions need to be normalized (e.g., find and replace "\r\n" with "\n" on the input and output when doing the assertions).

2023-12-18 18:34 UTC, mtdowling commented on smithy-model/src/main/java/software/amazon/smithy/model/node/Node.java
> +    public static String prettyPrintJsonWithBackticks(Node node) {
I don't think this should be something on Node itself. I think this could go in ValidationUtils.

2023-12-18 18:34 UTC, mtdowling commented on smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/TraitBreakingChange.java
> +                    } else if (Node.objectNode().equals(right.toNode())) {
I don't think you need .toNode on right here, or below on line 234

2023-12-18 18:34 UTC, mtdowling commented on smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/ModifiedTrait.java
> +                String leftPretty = Node.prettyPrintJsonWithBackticks(left.toNode());
don't need .toNode on left or right. I know it was there before, but this is a good time to fix it.

2024-01-24 16:27 UTC, mtdowling approved these changes

2024-01-24 16:30 UTC, merged