Make UnreferencedShape an opt-in linter instead
smithy-lang/smithy pull request #2119
Opened 2024-01-30 23:28 UTC by mtdowling

UnreferencedShape is no longer an on-by-default validator that ensures shapes must be connected to a service shape. There are plenty of cases where teams might create models that define shared shapes and don't necessarily connect those shapes to services. Emitting an UnreferencedShape validation event for these cases is harmless, but also annoying and desensitizing developers for when a shape is actually unreferenced.

This commit instead adds a new smithy-linters validator called UnreferencedShape that allows an optional "rootShapeSelector" to be provided that defines the "root" shapes that all other shape must be connected to. It defaults to "service". You might want to customize this to indicate that other shapes are your roots (e.g., maybe there is a specific trait that makes a shape a root).

Closes #2093

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-01-31 22:06 UTC, JordonPhillips requested changes
Also moving this back to smithy-model would be nice

2024-01-31 22:06 UTC, JordonPhillips commented on smithy-linters/src/main/java/software/amazon/smithy/linters/UnreferencedShapeValidator.java
> +public final class UnreferencedShapeValidator extends AbstractValidator {
public classes need docs

2024-02-08 06:43 UTC, kstich commented on smithy-model/src/test/java/software/amazon/smithy/model/loader/ValidationEventDecoratorTest.java
> +            System.out.println(ev);
```suggestion

```

2024-02-08 22:38 UTC, kstich approved these changes

2024-02-08 22:47 UTC, merged