Add defaults tests for restJson1
smithy-lang/smithy pull request #2280
Opened 2024-05-08 19:58 UTC by mullermp

#### Background
Add defaults tests for restJson1 similar to AwsJson1_0 and CBOR

#### Testing
In smithy-ruby, not sure how to test here.

#### Links
n/a

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-05-13 16:32 UTC, syall requested changes

2024-05-15 05:01 UTC, mullermp commented on smithy-aws-protocol-tests/model/restJson1/defaults.smithy
> +                    "default_string": "hi",
Yes, they should. I will change it.

2024-05-15 05:08 UTC, mullermp commented on smithy-aws-protocol-tests/model/restJson1/defaults.smithy
> +apply OperationWithDefaults @httpRequestTests([
It didn't apply to us. I can add them too.

2024-05-15 22:13 UTC, alextwoods commented on smithy-aws-protocol-tests/model/restJson1/defaults.smithy
> +apply OperationWithDefaults @httpRequestTests([
I've added the server tests.

2024-05-15 22:13 UTC, alextwoods commented on smithy-aws-protocol-tests/model/restJson1/defaults.smithy
> +                    "default_string": "hi",
I've updated all of the serialized member names.

2024-05-15 22:15 UTC, mullermp commented
@syall Alex made the changes while I am away. Please re-review.

2024-05-29 18:09 UTC, milesziemer approved these changes

2024-05-29 18:13 UTC, mullermp commented
Thank you!

2024-05-29 18:18 UTC, syall approved these changes

2024-05-29 18:25 UTC, merged