fix(cors): maps all unique operation mime types in cors preflight
smithy-lang/smithy pull request #2290
Opened 2024-05-17 02:42 UTC by jfkisafk

#### Background
* What do these changes do? 
 * Maps all the 
* Why are they important?

#### Testing
* How did you test these changes?

#### Links
* closes smithy-lang/smithy#2289

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-05-21 00:40 UTC, jfkisafk commented
Please lmk if this feature should be launched behind a feature flag in openapi settings or if I need to update the docs as well?

2024-05-22 04:32 UTC, kstich requested changes

2024-05-22 04:32 UTC, kstich commented on smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/AddCorsPreflightIntegration.java
> +                .passThroughBehavior(isPreflightSynced ? "never" : "when_no_match")
Can there be a link to [the `passThroughBehavior` docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/integration-passthrough-behaviors.html) here?

2024-05-22 04:32 UTC, kstich commented on docs/source-2.0/guides/model-translations/converting-to-openapi.rst
> +    With this enabled, the ``passthroughBehavior`` for the CORS preflight integration
Can there be a link to [the passThroughBehavior docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/integration-passthrough-behaviors.html) here?

2024-05-22 17:34 UTC, kstich commented on docs/source-2.0/guides/model-translations/converting-to-openapi.rst
> +.. _generate-openapi-setting-syncCorsPreflightIntegration:
This setting is API-Gateway specific, so should be moved down to [the API Gateway settings section](https://github.com/smithy-lang/smithy/blob/main/docs/source-2.0/guides/model-translations/converting-to-openapi.rst?plain=1#L1450). It's worth also adding a note to [the API Gateway specific CORS section](https://github.com/smithy-lang/smithy/blob/main/docs/source-2.0/guides/model-translations/converting-to-openapi.rst?plain=1#L1645).

2024-05-22 17:35 UTC, kstich commented on docs/source-2.0/guides/model-translations/converting-to-openapi.rst
> +.. _generate-openapi-setting-syncCorsPreflightIntegration:
```suggestion
.. _generate-openapi-apigateway-setting-syncCorsPreflightIntegration:
```

2024-05-22 19:03 UTC, kstich approved these changes

2024-05-22 19:03 UTC, merged